server:
  port: 8090

spring:
  profiles:
    active: ${ENVIRONMENT:local}
  application:
    name: melina
  web:
    resources:
      add-mappings: false    # Handle NoHandlerFoundException 需要
  mvc:
    throw-exception-if-no-handler-found: true    # Handle NoHandlerFoundException 需要

logging:
  config: classpath:logback/configuration.xml
